# Generated by Django 3.1.5 on 2021-01-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210129_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, default='/static/assets/img/blog/blog-1.jpg', null=True, upload_to='banners/'),
        ),
    ]
