# Generated by Django 3.1.5 on 2021-01-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210129_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, default='/banners/blog-1.jpg', null=True, upload_to='banners/'),
        ),
    ]
